FROM node

RUN mkdir -p /usr/local/appview/lib && \
    mkdir -p /usr/local/appview/bin

WORKDIR /usr/local/appview/

RUN npm install hot-shots && \
    apt-get -o Acquire::Check-Valid-Until=false update && \
    apt-get install -y vim gawk gdb emacs lsof tcpdump wget curl netcat-openbsd

COPY node/appview-test /usr/local/appview/
COPY node/hotshot.ts /usr/local/appview/
COPY node/client.js /usr/local/appview/
COPY node/server.js /usr/local/appview/

ENV APPVIEW_CRIBL_ENABLE=false

RUN cd /usr/local/appview && \
    openssl genpkey -algorithm RSA -out key.pem && \
    openssl req -new -key key.pem -out csr.pem -subj "/CN=example.com" && \
    openssl x509 -req -days 365 -in csr.pem -signkey key.pem -out cert.pem

RUN ln -s /opt/appview/bin/linux/$(uname -m)/appview /usr/local/appview/bin/appview

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["test"]
