FROM centos:7

ADD https://cdn.cribl.io/dl/lb/java/jre/jre-6u45-linux-x64-rpm.bin /tmp/jre-rpm.bin
WORKDIR /tmp
RUN chmod +x ./jre-rpm.bin && \
    ./jre-rpm.bin && \
    rm -f jre-*

WORKDIR /
ARG TOMCAT_MAJOR_VERSION=8
ARG TOMCAT_MINOR_VERSION=8.0.49
ARG KEYTOOL=keytool

ENV CATALINA_HOME /opt/tomcat
ENV PATH $PATH:$CATALINA_HOME/bin

ADD https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz /apache-tomcat.tar.gz

RUN tar zxf apache-tomcat.tar.gz && \
    rm apache-tomcat.tar.gz && \
    mv apache-tomcat* $CATALINA_HOME

RUN mkdir /opt/tomcat/certs && \
    mkdir -p /opt/test-runner/logs && \
    mkdir -p /opt/test-runner/bin

RUN ${KEYTOOL} -genkey -alias "tomcat" -dname "CN=appview,O=cribl" -keyalg RSA -storetype pkcs12 -keystore /opt/tomcat/certs/tomcat.p12 -storepass changeit -keypass changeit

COPY ./java/server.xml $CATALINA_HOME/conf/server.xml
COPY ./java/test-ssl.sh /opt/test-runner/bin/test-ssl.sh
RUN chmod +x /opt/test-runner/bin/test-ssl.sh

RUN mkdir -p /opt/javassl
COPY ./java/SSLSocketClient.class /opt/javassl/SSLSocketClient.class

RUN mkdir -p /opt/java_http
COPY ./java/SimpleHttpServer.class /opt/java_http/SimpleHttpServer.class
COPY ./java/'SimpleHttpServer$StatusHandler.class' /opt/java_http/'SimpleHttpServer$StatusHandler.class'

ENV APPVIEW_CRIBL_ENABLE=false
ENV APPVIEW_LOG_LEVEL=debug
ENV APPVIEW_METRIC_VERBOSITY=4
ENV APPVIEW_EVENT_LOGFILE=false
ENV APPVIEW_EVENT_CONSOLE=false
ENV APPVIEW_EVENT_METRIC=false
ENV APPVIEW_EVENT_HTTP=true
ENV APPVIEW_SUMMARY_PERIOD=1
ENV APPVIEW_EVENT_DEST=file:///opt/test-runner/logs/events.log
ENV APPVIEW_METRIC_DEST=udp://localhost:8125
ENV APPVIEW_LOG_DEST=file:///opt/test-runner/logs/appview.log
ENV CURL_PARAMS="--ciphers rsa_aes_128_sha"

COPY appview-profile.sh /etc/profile.d/appview.sh
COPY gdbinit /root/.gdbinit

RUN  mkdir /usr/local/appview && \
     mkdir /usr/local/appview/bin && \
     mkdir /usr/local/appview/lib && \
     ln -s /opt/appview/bin/linux/$(uname -m)/appview /usr/local/appview/bin/appview && \
     ln -s /opt/appview/lib/linux/$(uname -m)/libappview.so /usr/local/appview/lib/libappview.so

COPY java/appview-test /usr/local/appview/appview-test

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["test"]

