FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update \
    && apt install -y \
      curl \
      emacs \
      gcc \
      gdb \
      lsof \
      openjdk-13-jdk-headless \
      vim \
      wget \
    && rm -rf /var/lib/apt/lists/*

# Tests
COPY ./attach/test_attach.sh /opt/test/bin/test_attach.sh

RUN mkdir -p /opt/java_http
COPY ./java/SimpleHttpServer.java /opt/java_http/SimpleHttpServer.java
RUN javac -d /opt/java_http/ /opt/java_http/SimpleHttpServer.java

RUN mkdir -p /opt/exec_test
COPY ./attach/hello_exec.c /opt/exec_test/hello_exec.c
RUN gcc -O0 -g -o /opt/exec_test/exec_test /opt/exec_test/hello_exec.c

RUN mkdir -p /opt/implicit_deny
COPY ./attach/dummyproc.c /opt/implicit_deny/dummyproc.c
RUN gcc -O0 -g -o /opt/implicit_deny/systemd-networkd /opt/implicit_deny/dummyproc.c

RUN mkdir -p /opt/implicit_allow
COPY ./attach/dummyproc.c /opt/implicit_allow/dummyproc.c
RUN gcc -O0 -g -o /opt/implicit_allow/runc /opt/implicit_deny/dummyproc.c

RUN mkdir -p /opt/test_config
COPY ./attach/appview_test_cfg.yml /opt/test_config/appview_test_cfg.yml

ENV APPVIEW_CRIBL_ENABLE=false
ENV APPVIEW_LOG_LEVEL=error
ENV APPVIEW_METRIC_VERBOSITY=4
ENV APPVIEW_EVENT_LOGFILE=true
ENV APPVIEW_EVENT_CONSOLE=true
ENV APPVIEW_EVENT_METRIC=true
ENV APPVIEW_EVENT_HTTP=true
ENV APPVIEW_EVENT_NET=true
ENV APPVIEW_EVENT_FS=true
ENV APPVIEW_LOG_DEST=file:///opt/test-runner/logs/appview.log
ENV APPVIEW_EVENT_DEST=file:///opt/test-runner/logs/events.log
ENV LIB_IS_GLIBC=true

ENV PATH="/usr/local/appview:/usr/local/appview/bin:${PATH}"
COPY appview-profile.sh /etc/profile.d/appview.sh
COPY gdbinit /root/.gdbinit

RUN  mkdir /usr/local/appview && \
     mkdir /usr/local/appview/bin && \
     mkdir /usr/local/appview/lib && \
     mkdir -p /opt/test-runner/logs/ && \
     ln -s /opt/appview/bin/linux/$(uname -m)/appview /usr/local/appview/bin/appview && \
     ln -s /opt/appview/lib/linux/$(uname -m)/libappview.so /usr/local/appview/lib/libappview.so

COPY ./attach/dummy_rules /opt/test-runner/dummy_rules
COPY attach/appview-test /usr/local/appview/appview-test

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["test"]
