FROM alpine:3.16

RUN apk add bash nginx openrc pcre-tools

RUN rc-update add nginx default\
  && mkdir /run/openrc\
  && touch /run/openrc/softlevel

ENV APPVIEW_CRIBL_ENABLE=false

ENV PATH="/usr/local/appview:/usr/local/appview/bin:${PATH}"
COPY appview-profile.sh /etc/profile.d/appview.sh
COPY gdbinit /root/.gdbinit

RUN  mkdir /usr/local/appview && \
     mkdir /usr/local/appview/bin && \
     mkdir /usr/local/appview/lib && \
     ln -s /opt/appview/bin/linux/$(uname -m)/appview /usr/local/appview/bin/appview && \
     ln -s /opt/appview/lib/linux/$(uname -m)/libappview.so /usr/local/appview/lib/libappview.so

COPY service/appview-test.openrc.sh /usr/local/appview/appview-test

RUN rc-status

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["test"]
