FROM amazonlinux:2

RUN yum install -y tar gzip pcre-tools

RUN ARCH=$(uname -m | sed -e 's/x86_64/x64/' -e 's/aarch64/arm64/') \
 && curl -Lo /tmp/cribl.tgz https://cdn.cribl.io/dl/3.1.0/cribl-3.1.0-f765e418-linux-${ARCH}.tgz \
 && cd /opt \
 && tar zxf /tmp/cribl.tgz \
 && /opt/cribl/bin/cribl boot-start enable -m initd \
 && rm -f /tmp/cribl.tgz

ENV APPVIEW_CRIBL_ENABLE=false

ENV PATH="/usr/local/appview:/usr/local/appview/bin:${PATH}"
COPY appview-profile.sh /etc/profile.d/appview.sh
COPY gdbinit /root/.gdbinit

RUN  mkdir /usr/local/appview && \
     mkdir /usr/local/appview/bin && \
     mkdir /usr/local/appview/lib && \
     ln -s /opt/appview/bin/linux/$(uname -m)/appview /usr/local/appview/bin/appview && \
     ln -s /opt/appview/lib/linux/$(uname -m)/libappview.so /usr/local/appview/lib/libappview.so

COPY service/appview-test.initd.sh /usr/local/appview/appview-test

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["test"]
